In [10]:
# source : source: https://dziganto.github.io/data%20science/linear%20regression/machine%20learning/python/Linear-Regression-101-Basics/
# Simple Linear Regression without using SciKit or Spark ML

In [2]:
# import required libraries
import numpy as np
# reproducibility
np.random.seed(10)

In [3]:
# generate some data
babies = range(10)
months = np.arange(13)

In [4]:
babies

range(0, 10)

In [5]:
list(babies)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
months

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [7]:
# create fake data
data = [(month, np.dot(month, 24.7) + 96 + np.random.normal(loc=0, scale=20)) for month in months for baby in babies]
data

[(0, 122.63173008259037),
 (0, 110.30557948796812),
 (0, 65.09199415777464),
 (0, 95.83232300142956),
 (0, 108.42671947780961),
 (0, 81.59828878562206),
 (0, 101.31023171384238),
 (0, 98.17097051429938),
 (0, 96.08582861868067),
 (0, 92.50799578814117),
 (1, 129.36052379907196),
 (1, 144.76074747624423),
 (1, 101.39868658966473),
 (1, 141.2654815596541),
 (1, 125.2726026024932),
 (1, 129.60275225660695),
 (1, 97.96795576337912),
 (1, 123.40273756897271),
 (1, 150.39074003673164),
 (1, 99.10390228429449),
 (2, 105.84543438684187),
 (2, 110.53255408202186),
 (2, 150.72140328001103),
 (2, 193.09934661422193),
 (2, 167.87382506818847),
 (2, 178.85244426615657),
 (2, 147.3829843167049),
 (2, 173.3599275418715),
 (2, 139.9750402406844),
 (2, 157.66408369719278),
 (3, 164.75365622652862),
 (3, 159.1138197178904),
 (3, 172.75416591519902),
 (3, 160.57715970145324),
 (3, 196.26946161726954),
 (3, 174.00026558466186),
 (3, 178.10419976504696),
 (3, 163.3473532582894),
 (3, 195.2294452751031),
 (

In [8]:
month_data = [element[0] for element in data]
month_data

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12]

In [9]:
weight_data = [element[1] for element in data]
weight_data

[122.63173008259037,
 110.30557948796812,
 65.09199415777464,
 95.83232300142956,
 108.42671947780961,
 81.59828878562206,
 101.31023171384238,
 98.17097051429938,
 96.08582861868067,
 92.50799578814117,
 129.36052379907196,
 144.76074747624423,
 101.39868658966473,
 141.2654815596541,
 125.2726026024932,
 129.60275225660695,
 97.96795576337912,
 123.40273756897271,
 150.39074003673164,
 99.10390228429449,
 105.84543438684187,
 110.53255408202186,
 150.72140328001103,
 193.09934661422193,
 167.87382506818847,
 178.85244426615657,
 147.3829843167049,
 173.3599275418715,
 139.9750402406844,
 157.66408369719278,
 164.75365622652862,
 159.1138197178904,
 172.75416591519902,
 160.57715970145324,
 196.26946161726954,
 174.00026558466186,
 178.10419976504696,
 163.3473532582894,
 195.2294452751031,
 155.46060995997584,
 208.00463102452628,
 187.78256217120258,
 176.01133280474897,
 185.013255662307,
 178.70817715460092,
 190.54604722578978,
 188.0171950787313,
 201.04339872626446,
 206.103053

In [11]:
# create X
X = np.array(month_data)
X = np.c_[np.ones(X.shape[0]), X] # little trick to add vector of 1's
y = np.array(weight_data)

In [12]:
X

array([[ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  2.],
       [ 1.,  2.],
       [ 1.,  2.],
       [ 1.,  2.],
       [ 1.,  2.],
       [ 1.,  2.],
       [ 1.,  2.],
       [ 1.,  2.],
       [ 1.,  2.],
       [ 1.,  2.],
       [ 1.,  3.],
       [ 1.,  3.],
       [ 1.,  3.],
       [ 1.,  3.],
       [ 1.,  3.],
       [ 1.,  3.],
       [ 1.,  3.],
       [ 1.,  3.],
       [ 1.,  3.],
       [ 1.,  3.],
       [ 1.,  4.],
       [ 1.,  4.],
       [ 1.,  4.],
       [ 1.,  4.],
       [ 1.,  4.],
       [ 1.,  4.],
       [ 1.,  4.],
       [ 1.,  4.],
       [ 1.,  4.],
       [ 1.,  4.],
       [ 1.,  5.],
       [ 1.,  5.],
       [ 1.,

In [13]:
y

array([122.63173008, 110.30557949,  65.09199416,  95.832323  ,
       108.42671948,  81.59828879, 101.31023171,  98.17097051,
        96.08582862,  92.50799579, 129.3605238 , 144.76074748,
       101.39868659, 141.26548156, 125.2726026 , 129.60275226,
        97.96795576, 123.40273757, 150.39074004,  99.10390228,
       105.84543439, 110.53255408, 150.72140328, 193.09934661,
       167.87382507, 178.85244427, 147.38298432, 173.35992754,
       139.97504024, 157.6640837 , 164.75365623, 159.11381972,
       172.75416592, 160.5771597 , 196.26946162, 174.00026558,
       178.10419977, 163.34735326, 195.22944528, 155.46060996,
       208.00463102, 187.78256217, 176.0113328 , 185.01325566,
       178.70817715, 190.54604723, 188.01719508, 201.04339873,
       206.10305339, 191.85159485, 218.98189326, 225.28188408,
       208.70241857, 233.6632004 , 236.34449477, 223.57161595,
       267.3940733 , 237.84917875, 217.25455058, 212.25639106,
       239.55635488, 234.16542201, 266.77570306, 230.24

In [14]:
def ols(X, y):
     '''returns parameters based on Ordinary Least Squares.'''
     xtx = np.dot(X.T, X) ## x-transpose times x
     inv_xtx = np.linalg.inv(xtx) ## inverse of x-transpose times x
     xty = np.dot(X.T, y) ## x-transpose times y
     return np.dot(inv_xtx, xty)
    

In [15]:
params = ols(X,y)
print('intercept: {} | slope: {}'.format(params[0], params[1]))

intercept: 97.94349022705853 | slope: 24.680165065438743
