In [1]:
# Naive Bayes Classification using Scikit-learn

In [2]:
weather=['Sunny','Sunny','Overcast','Rainy','Rainy','Rainy','Overcast','Sunny','Sunny',
'Rainy','Sunny','Overcast','Overcast','Rainy']
temp=['Hot','Hot','Hot','Mild','Cool','Cool','Cool','Mild','Cool','Mild','Mild','Mild','Hot','Mild']

play=['No','No','Yes','Yes','Yes','No','Yes','No','Yes','Yes','Yes','Yes','Yes','No']

In [4]:
weather

['Sunny',
 'Sunny',
 'Overcast',
 'Rainy',
 'Rainy',
 'Rainy',
 'Overcast',
 'Sunny',
 'Sunny',
 'Rainy',
 'Sunny',
 'Overcast',
 'Overcast',
 'Rainy']

In [5]:
len(weather)

14

In [6]:
temp

['Hot',
 'Hot',
 'Hot',
 'Mild',
 'Cool',
 'Cool',
 'Cool',
 'Mild',
 'Cool',
 'Mild',
 'Mild',
 'Mild',
 'Hot',
 'Mild']

In [7]:
len(temp)

14

In [8]:
play

['No',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'No']

In [9]:
len(play)

14

In [10]:
# Encoding Features
# First, you need to convert these string labels into numbers

In [14]:
# Import LabelEncoder
from sklearn import preprocessing
#creating labelEncoder
le = preprocessing.LabelEncoder()
# Converting string labels into numbers.
weather_encoded=le.fit_transform(weather)

In [15]:
weather_encoded

array([2, 2, 0, 1, 1, 1, 0, 2, 2, 1, 2, 0, 0, 1])

In [16]:
# Similarly, you can also encode temp and play columns.

In [18]:
# Converting string labels into numbers
temp_encoded=le.fit_transform(temp)
label=le.fit_transform(play)

In [19]:
temp_encoded

array([1, 1, 1, 2, 0, 0, 0, 2, 0, 2, 2, 2, 1, 2])

In [20]:
label

array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0])

In [21]:
# Now combine both the features (weather and temp) in a single variable (list of tuples).

In [22]:
features=zip(weather_encoded,temp_encoded)

In [23]:
features

In [24]:
for feature in features: print(feature)

(2, 1)
(2, 1)
(0, 1)
(1, 2)
(1, 0)
(1, 0)
(0, 0)
(2, 2)
(2, 0)
(1, 2)
(2, 2)
(0, 2)
(0, 1)
(1, 2)


In [25]:
#Generate a model using naive bayes classifier in the following steps:
#
# 1. Create naive bayes classifier
# 2. Fit the dataset on classifier
# 3. Perform prediction

In [27]:
#Import Gaussian Naive Bayes model
from sklearn.naive_bayes import GaussianNB

#Create a Gaussian Classifier
model = GaussianNB()


In [29]:
# features=zip(weather_encoded,temp_encoded)
import numpy as np
features = np.array(list(zip(weather_encoded,temp_encoded)))

In [30]:
features

array([[2, 1],
       [2, 1],
       [0, 1],
       [1, 2],
       [1, 0],
       [1, 0],
       [0, 0],
       [2, 2],
       [2, 0],
       [1, 2],
       [2, 2],
       [0, 2],
       [0, 1],
       [1, 2]])

In [31]:
model.fit(features,label)

GaussianNB(priors=None, var_smoothing=1e-09)

In [32]:
#Predict Output
predicted= model.predict([[0,2]]) # 0:Overcast, 2:Mild
print ("Predicted Value:", predicted)

Predicted Value: [1]


In [33]:
# Naive Bayes with Multiple Labels

In [34]:
# Dataset comprises of 13 features:
# (alcohol, malic_acid, ash, alcalinity_of_ash, magnesium, total_phenols, flavanoids, nonflavanoid_phenols, proanthocyanins, color_intensity, hue, od280/od315_of_diluted_wines, proline) and type of wine cultivar. 
# This data has three type of wine Class_0, Class_1, and Class_2. 
# Here you can build a model to classify the type of wine.

In [37]:
#Import scikit-learn dataset library
from sklearn import datasets

#Load dataset
wine = datasets.load_wine()

In [38]:
# Exploring Data
# You can print the target and feature names, 
# to make sure you have the right dataset, as such:

In [39]:
# print the names of the 13 features
print ("Features: ", wine.feature_names)


Features:  ['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']


In [40]:
# print the label type of wine(class_0, class_1, class_2)
print ("Labels: ", wine.target_names)

Labels:  ['class_0' 'class_1' 'class_2']


In [41]:
# It's a good idea to always explore your data a bit, 
# so you know what you're working with. Here, you can see 
# the first five rows of the dataset are printed, as well as 
# the target variable for the whole dataset.

In [42]:
# print data(feature)shape
wine.data.shape

(178, 13)

In [44]:
# print the wine data features (top 5 records)
print (wine.data[0:5])

[[1.423e+01 1.710e+00 2.430e+00 1.560e+01 1.270e+02 2.800e+00 3.060e+00
  2.800e-01 2.290e+00 5.640e+00 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 1.120e+01 1.000e+02 2.650e+00 2.760e+00
  2.600e-01 1.280e+00 4.380e+00 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 1.860e+01 1.010e+02 2.800e+00 3.240e+00
  3.000e-01 2.810e+00 5.680e+00 1.030e+00 3.170e+00 1.185e+03]
 [1.437e+01 1.950e+00 2.500e+00 1.680e+01 1.130e+02 3.850e+00 3.490e+00
  2.400e-01 2.180e+00 7.800e+00 8.600e-01 3.450e+00 1.480e+03]
 [1.324e+01 2.590e+00 2.870e+00 2.100e+01 1.180e+02 2.800e+00 2.690e+00
  3.900e-01 1.820e+00 4.320e+00 1.040e+00 2.930e+00 7.350e+02]]


In [45]:
# print the wine labels (0:Class_0, 1:class_2, 2:class_2)
print (wine.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


In [46]:
# Splitting Data

In [48]:
# Import train_test_split function
from sklearn.model_selection import train_test_split

# Split dataset into training set and test set
# # 70% training and 30% test
X_train, X_test, y_train, y_test = train_test_split(wine.data, wine.target, test_size=0.3,random_state=109)

In [49]:
print("len(X_train)=", len(X_train))
print("len(X_test)=", len(X_test))
print("len(y_train)=", len(y_train))
print("len(y_test)=", len(y_test))

len(X_train)= 124
len(X_test)= 54
len(y_train)= 124
len(y_test)= 54


In [50]:
# Model Generation
# After splitting, you will generate a random forest model on the 
# training set and perform prediction on test set features.

In [51]:
#Import Gaussian Naive Bayes model
from sklearn.naive_bayes import GaussianNB

#Create a Gaussian Classifier
gnb = GaussianNB()

#Train the model using the training sets
gnb.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [52]:
#Predict the response for test dataset
y_pred = gnb.predict(X_test)

In [53]:
# Evaluating Model
# After model generation, check the accuracy using actual and predicted values.

In [54]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.9074074074074074
